apiVersion: v1
kind: Service
metadata:
    name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port : 8080     # service
      #targetPort: 8081 #container
      nodePort: 30000 #cluster
  type: NodePort